classes = {
    0: {
        "description": "01+02_누적고무",
        "name": "accumulated",
        "color": (0, 0, 255),
        "pass": False,
    },
    1: {
        "description": "01-00_고무테두리",
        "name": "edge",
        "color": (255, 255, 255),
        "pass": True,
    },
    2: {
        "description": "01-01_꼬마부스러기",
        "name": "tiny_debris",
        "color": (255, 255, 255),
        "pass":True,
    },
    3: {
        "description": "01-02_날씬및쭈끌고무",
        "name": "unformed",
        "color": (255, 255, 255),
        "pass": True,
    },
    4: {
        "description": "01-04_대왕부스러기",
        "name": "debris",
        "color": (255, 255, 255),
        "pass": True,
    },
    5: {
        "description": "01-05_베일러",
        "name": "baler",
        "color": (255, 255, 255),
        "pass":True,
    },
    6: {
        "description": "01-06_보통의고무들",
        "name": "rubber",
        "color": (255, 255, 255),
        "pass":True,
    },
    7: {
        "description": "01-07_성형불량",
        "name": "cosmetic",
        "color": (255, 255, 255),
        "pass": True,
    },
    8: {
        "description": "01-08_수분",
        "name": "wet",
        "color": (255, 255, 255),
        "pass":True,
    },
    9: {
        "description": "01-09_이물",
        "name": "foreign",
        "color": (255, 255, 255),
        "pass":True,
    },
    10: {
        "description": "01-10_이미지디비",
        "name": "inspector",
        "color": (255, 255, 255),
        "pass":True,
    },
    11: {
        "description": "01-11_지렁이",
        "name": "worm",
        "color": (255, 255, 255),
        "pass": True,
    },
    12: {
        "description": "02+03_점이물",
        "name": "foreign",
        "color": ( 0, 0, 255),
        "pass":False,
    },
    13: {
        "description": "02-0_그냥고무",
        "name": "rubber",
        "color": (255, 255, 255),
        "pass": True,
    },
    14: {
        "description": "03-1-2_누적고무_경계불분명",
        "name": "accumulated",
        "color": ( 0, 0, 255),
        "pass":False,
    },
    15: {
        "description": "03-2-1_이물_점보다는크고더러움",
        "name": "foreign",
        "color": ( 0, 0, 255),
        "pass":False,
    },
    16: {
        "description": "03_점이물쓰레기통-눈알두개",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    17: {
        "description": "03_점이물쓰레기통-뭘까",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    18: {
        "description": "03_점이물쓰레기통-테두리쪽-아래",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    19: {
        "description": "03_점이물쓰레기통-테두리쪽-옆-지렁이같은거",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    20: {
        "description": "03_점이물쓰레기통-테두리쪽-옆모서리",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    21: {
        "description": "03_점이물쓰레기통-허옇다",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
    22: {
        "description": "04_실지렁이",
        "name": "dot_trash",
        "color": (255, 255, 255),
        "pass": True,
    },
}